namespace AgenticSystem.Core.Models;

// ═══════════════════════════════════════════════════════════
// #42 — Dependency Graph
// ═══════════════════════════════════════════════════════════

/// <summary>
/// System dependency node for impact analysis.
/// </summary>
public class DependencyNode
{
    public string Id { get; init; } = string.Empty;
    public string Name { get; init; } = string.Empty;
    public DependencyType Type { get; init; }
    public DependencyHealth Health { get; set; } = DependencyHealth.Healthy;
    public List<string> DependsOn { get; init; } = [];
    public List<string> DependedBy { get; init; } = [];
    public Dictionary<string, string> Metadata { get; init; } = new();
}

public enum DependencyType { Agent, Tool, Service, Database, ExternalApi, McpServer, Model }
public enum DependencyHealth { Healthy, Degraded, Unhealthy, Unknown }

/// <summary>
/// Impact analysis result for a dependency change.
/// </summary>
public class ImpactAnalysis
{
    public string ChangedNodeId { get; init; } = string.Empty;
    public List<string> DirectlyAffected { get; init; } = [];
    public List<string> IndirectlyAffected { get; init; } = [];
    public int TotalImpactedNodes { get; init; }
    public double SeverityScore { get; init; }
}

// ═══════════════════════════════════════════════════════════
// #43 — AG-UI Runtime
// ═══════════════════════════════════════════════════════════

/// <summary>
/// A UI component dynamically generated by an agent.
/// </summary>
public class AgentUIComponent
{
    public string Id { get; init; } = Guid.NewGuid().ToString("N");
    public string AgentName { get; init; } = string.Empty;
    public UIComponentType ComponentType { get; init; }
    public string Title { get; init; } = string.Empty;
    public Dictionary<string, object> Props { get; init; } = new();
    public List<AgentUIComponent> Children { get; init; } = [];
    public string? ActionEndpoint { get; init; }
}

public enum UIComponentType
{
    Card, Form, Table, Chart, Alert,
    Button, Input, Select, Markdown,
    ProgressBar, Timeline, KanbanBoard
}

// ═══════════════════════════════════════════════════════════
// #44 — SLA / QoS Tiers
// ═══════════════════════════════════════════════════════════

/// <summary>
/// Service level agreement tier configuration.
/// </summary>
public class SlaTier
{
    public string Id { get; init; } = string.Empty;
    public string Name { get; init; } = string.Empty; // "Free", "Standard", "Premium"
    public double MaxLatencyMs { get; init; }
    public double UptimeTarget { get; init; } = 99.9;
    public int MaxConcurrentRequests { get; init; }
    public int MaxTokensPerRequest { get; init; }
    public int PriorityLevel { get; init; } // Higher = processed first
    public List<string> AvailableModels { get; init; } = [];
    public bool DedicatedResources { get; init; }
    public double MonthlyPriceUsd { get; init; }
}

// ═══════════════════════════════════════════════════════════
// #45 — Deployment Isolation
// ═══════════════════════════════════════════════════════════

/// <summary>
/// Deployment configuration for runtime isolation.
/// </summary>
public class DeploymentConfig
{
    public string TenantId { get; init; } = string.Empty;
    public DeploymentMode Mode { get; init; } = DeploymentMode.Shared;
    public string? ContainerImage { get; init; }
    public int WorkerPoolSize { get; init; } = 2;
    public int MaxMemoryMb { get; init; } = 512;
    public int MaxCpuMillicores { get; init; } = 500;
    public string? Region { get; init; }
    public Dictionary<string, string> EnvironmentVariables { get; init; } = new();
}

public enum DeploymentMode { Shared, DedicatedWorker, DedicatedContainer, DedicatedCluster }

// ═══════════════════════════════════════════════════════════
// #46 — Admin Console
// ═══════════════════════════════════════════════════════════

/// <summary>
/// Admin dashboard summary.
/// </summary>
public class AdminDashboard
{
    public int TotalAgents { get; init; }
    public int ActiveSessions { get; init; }
    public int PendingApprovals { get; init; }
    public int DeadLetterCount { get; init; }
    public double TotalCostToday { get; init; }
    public int RequestsToday { get; init; }
    public List<AdminAlert> ActiveAlerts { get; init; } = [];
    public Dictionary<string, DependencyHealth> SystemHealth { get; init; } = new();
}

public class AdminAlert
{
    public string Id { get; init; } = Guid.NewGuid().ToString("N");
    public string Message { get; init; } = string.Empty;
    public AdminAlertSeverity Severity { get; init; }
    public DateTime Timestamp { get; init; } = DateTime.UtcNow;
}

public enum AdminAlertSeverity { Info, Warning, Error, Critical }

// ═══════════════════════════════════════════════════════════
// #47 — Explainability
// ═══════════════════════════════════════════════════════════

/// <summary>
/// Explanation of an agent's decision-making process.
/// </summary>
public class DecisionExplanation
{
    public string DecisionId { get; init; } = Guid.NewGuid().ToString("N");
    public string AgentName { get; init; } = string.Empty;
    public string Question { get; init; } = string.Empty;
    public string Answer { get; init; } = string.Empty;
    public List<ReasoningStep> ReasoningChain { get; init; } = [];
    public List<string> SourcesUsed { get; init; } = [];
    public List<string> ToolsUsed { get; init; } = [];
    public double ConfidenceScore { get; init; }
    public List<string> Uncertainties { get; init; } = [];
    public string? AlternativeApproach { get; init; }
    public DateTime Timestamp { get; init; } = DateTime.UtcNow;
}

public class ReasoningStep
{
    public int Order { get; init; }
    public string Title { get; init; } = string.Empty;
    public string StepType { get; init; } = string.Empty; // "retrieval", "analysis", "inference", "tool_call"
    public string Description { get; init; } = string.Empty;
    public double Confidence { get; init; }
    public string? Evidence { get; init; }
}

// ═══════════════════════════════════════════════════════════
// #48 — Capability Negotiation (A2A/MCP)
// ═══════════════════════════════════════════════════════════

/// <summary>
/// Capability advertisement for A2A/MCP discovery protocol.
/// </summary>
public class AgentCapabilityCard
{
    public string AgentId { get; init; } = string.Empty;
    public string Name { get; init; } = string.Empty;
    public string Description { get; init; } = string.Empty;
    public string Version { get; init; } = "1.0";
    public string Protocol { get; init; } = "A2A"; // "A2A" | "MCP"
    public string? EndpointUrl { get; init; }
    public List<string> SupportedInputTypes { get; init; } = [];
    public List<string> SupportedOutputTypes { get; init; } = [];
    public List<string> Skills { get; init; } = [];
    public AuthenticationRequirement Authentication { get; init; } = new();
}

public class AuthenticationRequirement
{
    public string Method { get; init; } = "bearer"; // "bearer", "api_key", "oauth2", "none"
    public string? Scope { get; init; }
}

// ═══════════════════════════════════════════════════════════
// #49 — Agent Communication Protocol
// ═══════════════════════════════════════════════════════════

/// <summary>
/// A formal message in the inter-agent communication protocol.
/// </summary>
public class AgentMessage
{
    public string MessageId { get; init; } = Guid.NewGuid().ToString("N");
    public string SenderId { get; init; } = string.Empty;
    public string ReceiverId { get; init; } = string.Empty;
    public AgentMessageType MessageType { get; init; }
    public string Content { get; init; } = string.Empty;
    public Dictionary<string, object> Payload { get; init; } = new();
    public string? ConversationId { get; init; }
    public string? InReplyTo { get; init; }
    public AgentMessagePriority Priority { get; init; } = AgentMessagePriority.Normal;
    public DateTime Timestamp { get; init; } = DateTime.UtcNow;
    public DateTime? ExpiresAt { get; init; }
}

public enum AgentMessageType
{
    Request,
    Response,
    Delegation,
    Notification,
    Handoff,
    StatusUpdate,
    ErrorReport,
    CapabilityQuery
}

public enum AgentMessagePriority { Low, Normal, High, Urgent }
