// <auto-generated />
using System;
using System.Collections.Generic;
using AgenticSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgenticSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgenticDbContext))]
    [Migration("20260509022353_AddAuditIpAndUserAgent")]
    partial class AddAuditIpAndUserAgent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgenticSystem.Core.Models.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Limits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("limits");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plan");

                    b.Property<string>("ProviderApiKeys")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("provider_api_keys");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_tenants_is_active");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.AgentMemoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("agent_name");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("KeywordsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("keywords");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("memory_type");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AgentName")
                        .HasDatabaseName("ix_agent_memories_agent_name");

                    b.HasIndex("LastUsedAt")
                        .HasDatabaseName("ix_agent_memories_last_used_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_agent_memories_user_id");

                    b.HasIndex("UserId", "AgentName")
                        .HasDatabaseName("ix_agent_memories_user_agent");

                    b.ToTable("agent_memories", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.AgentPerformanceMetricEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("agent_name");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("domain");

                    b.Property<double>("LatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("latency_ms");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<double?>("UserSatisfaction")
                        .HasColumnType("double precision")
                        .HasColumnName("user_satisfaction");

                    b.HasKey("Id");

                    b.HasIndex("AgentName")
                        .HasDatabaseName("ix_agent_metrics_agent_name");

                    b.HasIndex("Domain")
                        .HasDatabaseName("ix_agent_metrics_domain");

                    b.HasIndex("AgentName", "Domain")
                        .HasDatabaseName("ix_agent_metrics_agent_domain");

                    b.ToTable("agent_performance_metrics", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.AgentPolicyEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AgentNamePattern")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.PrimitiveCollection<List<string>>("AllowedProviders")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("AllowedToolCategories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("ApprovalThreshold")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("ContentFilters")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("DeniedTools")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAutonomyLevel")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxCostPerDay")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MaxCostPerRequest")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("MaxTokensPerRequest")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<bool>("RequireFinalApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("TenantId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AgentPolicies");
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.AuditEntryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("action");

                    b.Property<string>("AgentName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("agent_name");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("ModelUsed")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_used");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("ToolName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tool_name");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_audit_entries_tenant_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_entries_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_entries_user_id");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.ConfigChangeLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("text")
                        .HasColumnName("changed_by");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("config_key");

                    b.Property<string>("NewValueHash")
                        .HasColumnType("text")
                        .HasColumnName("new_value_hash");

                    b.Property<string>("PreviousValueHash")
                        .HasColumnType("text")
                        .HasColumnName("previous_value_hash");

                    b.HasKey("Id");

                    b.HasIndex("ConfigKey", "ChangedAt")
                        .HasDatabaseName("ix_config_change_logs_key_changed_at");

                    b.ToTable("config_change_logs", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.ConfigEntryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EncryptedValue")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_value");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_config_entries_category");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("config_entries", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.CostBudgetEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(384)
                        .HasColumnType("character varying(384)")
                        .HasColumnName("id");

                    b.Property<decimal>("DailyBudget")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("daily_budget");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("service_name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ServiceName")
                        .IsUnique()
                        .HasDatabaseName("ix_cost_budgets_tenant_service");

                    b.ToTable("cost_budgets", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.CostEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("service_name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_cost_entries_recorded_at");

                    b.HasIndex("ServiceName")
                        .HasDatabaseName("ix_cost_entries_service_name");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_cost_entries_tenant_id");

                    b.HasIndex("TenantId", "ServiceName", "RecordedAt")
                        .HasDatabaseName("ix_cost_entries_tenant_service_date");

                    b.ToTable("cost_entries", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.EmbeddingModelEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_embedding_models_active");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_embedding_models_name");

                    b.ToTable("embedding_models", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.EvaluationScoreEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("agent_name");

                    b.Property<string>("AlertsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("alerts");

                    b.Property<double>("BaselineScore")
                        .HasColumnType("double precision")
                        .HasColumnName("baseline_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FactorsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("factors");

                    b.Property<double>("OverallScore")
                        .HasColumnType("double precision")
                        .HasColumnName("overall_score");

                    b.Property<bool>("RegressionDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("regression_detected");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.HasKey("Id");

                    b.HasIndex("AgentName")
                        .HasDatabaseName("ix_runtime_evaluations_agent_name");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_runtime_evaluations_created_at");

                    b.HasIndex("RegressionDetected")
                        .HasDatabaseName("ix_runtime_evaluations_regression");

                    b.ToTable("runtime_evaluations", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.MigrationJobEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_migration_jobs_created");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_migration_jobs_status");

                    b.ToTable("migration_jobs", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_created_at");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.ReflectionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_taken");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("agent_name");

                    b.Property<double>("ConfidenceInOutcome")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("deviations");

                    b.Property<string>("ImprovementSuggestion")
                        .HasColumnType("text")
                        .HasColumnName("improvement_suggestion");

                    b.Property<string>("LessonsLearnedJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lessons_learned");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("AgentName")
                        .HasDatabaseName("ix_runtime_reflections_agent_name");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_runtime_reflections_created_at");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_runtime_reflections_session_id");

                    b.ToTable("runtime_reflections", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.RerankingAssetEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("AssetType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("asset_type");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "AssetType");

                    b.ToTable("reranking_assets", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.RoleAssignmentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("granted_by");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_id");

                    b.Property<string>("TenantId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_role_assignments_tenant_id");

                    b.HasIndex("UserId", "RoleId", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_role_assignments_unique");

                    b.ToTable("role_assignments", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.RuntimeArtifactEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("AgentName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("agent_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("RelatedIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("related_ids");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_runtime_artifacts_created_at");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_runtime_artifacts_session_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_runtime_artifacts_type");

                    b.HasIndex("SessionId", "Type")
                        .HasDatabaseName("ix_runtime_artifacts_session_type");

                    b.ToTable("runtime_artifacts", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.RuntimeMetricsSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AgentExecutionCountsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("agent_execution_counts");

                    b.Property<long>("AgentExecutions")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_executions");

                    b.Property<long>("AgentFallbacks")
                        .HasColumnType("bigint")
                        .HasColumnName("agent_fallbacks");

                    b.Property<double>("AverageAgentLatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_agent_latency_ms");

                    b.Property<double>("AverageToolLatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_tool_latency_ms");

                    b.Property<string>("EventsByTypeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("events_by_type");

                    b.Property<long>("FinalApprovalsRequested")
                        .HasColumnType("bigint")
                        .HasColumnName("final_approvals_requested");

                    b.Property<long>("FinalApprovalsResolved")
                        .HasColumnType("bigint")
                        .HasColumnName("final_approvals_resolved");

                    b.Property<long>("Handoffs")
                        .HasColumnType("bigint")
                        .HasColumnName("handoffs");

                    b.Property<long>("RagQueries")
                        .HasColumnType("bigint")
                        .HasColumnName("rag_queries");

                    b.Property<long>("Reviews")
                        .HasColumnType("bigint")
                        .HasColumnName("reviews");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("SnapshotAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snapshot_at");

                    b.Property<long>("StreamCount")
                        .HasColumnType("bigint")
                        .HasColumnName("stream_count");

                    b.Property<long>("ToolApprovalsRequested")
                        .HasColumnType("bigint")
                        .HasColumnName("tool_approvals_requested");

                    b.Property<long>("ToolApprovalsResolved")
                        .HasColumnType("bigint")
                        .HasColumnName("tool_approvals_resolved");

                    b.Property<long>("ToolExecutions")
                        .HasColumnType("bigint")
                        .HasColumnName("tool_executions");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_runtime_metrics_session_id");

                    b.HasIndex("SnapshotAt")
                        .HasDatabaseName("ix_runtime_metrics_snapshot_at");

                    b.ToTable("runtime_metrics_snapshots", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.ScheduledTaskEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_scheduled_tasks_status");

                    b.ToTable("scheduled_tasks", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.ScheduledTaskExecutionEntity", b =>
                {
                    b.Property<string>("ExecutionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("execution_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("task_id");

                    b.HasKey("ExecutionId");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_scheduled_task_executions_task_id");

                    b.ToTable("scheduled_task_executions", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.SessionRecordEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<bool>("IsConsolidated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_consolidated");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("idx_sessions_started");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sessions_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.TriggerRuleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("ix_trigger_rules_enabled");

                    b.ToTable("trigger_rules", (string)null);
                });

            modelBuilder.Entity("AgenticSystem.Infrastructure.Persistence.Entities.VectorDocumentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("collection");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.PrimitiveCollection<float[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("real[]")
                        .HasColumnName("embedding");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Collection")
                        .HasDatabaseName("ix_vector_documents_collection");

                    b.HasIndex("IndexedAt")
                        .HasDatabaseName("ix_vector_documents_indexed_at");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_vector_documents_type");

                    b.ToTable("vector_documents", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
