CREATE TABLE IF NOT EXISTS __ef_migrations_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___ef_migrations_history" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE agent_memories (
        id character varying(64) NOT NULL,
        user_id character varying(256) NOT NULL,
        agent_name character varying(256) NOT NULL,
        session_id character varying(128),
        memory_type character varying(64) NOT NULL,
        content text NOT NULL,
        confidence double precision NOT NULL,
        source character varying(128) NOT NULL,
        keywords jsonb NOT NULL,
        metadata jsonb NOT NULL,
        created_at timestamp with time zone NOT NULL,
        last_used_at timestamp with time zone NOT NULL,
        usage_count integer NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT "PK_agent_memories" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE agent_performance_metrics (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        agent_name character varying(256) NOT NULL,
        domain character varying(128) NOT NULL,
        latency_ms double precision NOT NULL,
        success boolean NOT NULL,
        user_satisfaction double precision,
        recorded_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_agent_performance_metrics" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE config_change_logs (
        id character varying(128) NOT NULL,
        config_key character varying(256) NOT NULL,
        action character varying(64) NOT NULL,
        changed_by text,
        changed_at timestamp with time zone NOT NULL,
        previous_value_hash text,
        new_value_hash text,
        CONSTRAINT "PK_config_change_logs" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE config_entries (
        id character varying(128) NOT NULL,
        key character varying(256) NOT NULL,
        value text NOT NULL,
        encrypted_value text,
        is_secret boolean NOT NULL,
        category character varying(64) NOT NULL,
        status character varying(64) NOT NULL,
        description text,
        provider text,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        expires_at timestamp with time zone,
        metadata jsonb NOT NULL,
        CONSTRAINT "PK_config_entries" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE cost_budgets (
        id character varying(384) NOT NULL,
        service_name character varying(256) NOT NULL,
        tenant_id character varying(128) NOT NULL,
        daily_budget numeric(18,6) NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_cost_budgets" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE cost_entries (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        service_name character varying(256) NOT NULL,
        category character varying(128) NOT NULL,
        tenant_id character varying(128) NOT NULL,
        cost numeric(18,6) NOT NULL,
        recorded_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_cost_entries" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE embedding_models (
        id character varying(128) NOT NULL,
        name text NOT NULL,
        is_active boolean NOT NULL,
        data jsonb NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_embedding_models" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE migration_jobs (
        id character varying(128) NOT NULL,
        status character varying(64) NOT NULL,
        data jsonb NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_migration_jobs" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE reranking_assets (
        tenant_id character varying(128) NOT NULL,
        asset_type character varying(64) NOT NULL,
        file_name text NOT NULL,
        content_type text NOT NULL,
        content bytea NOT NULL,
        content_hash character varying(128) NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_reranking_assets" PRIMARY KEY (tenant_id, asset_type)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE runtime_artifacts (
        id character varying(64) NOT NULL,
        session_id character varying(128) NOT NULL,
        type character varying(64) NOT NULL,
        name character varying(256) NOT NULL,
        agent_name character varying(256),
        status character varying(64) NOT NULL,
        summary text,
        data jsonb NOT NULL,
        related_ids jsonb NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_runtime_artifacts" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE runtime_evaluations (
        id character varying(64) NOT NULL,
        session_id character varying(128),
        agent_name character varying(256),
        overall_score double precision NOT NULL,
        baseline_score double precision NOT NULL,
        threshold double precision NOT NULL,
        regression_detected boolean NOT NULL,
        factors jsonb NOT NULL,
        alerts jsonb NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_runtime_evaluations" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE runtime_metrics_snapshots (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        session_id character varying(128),
        stream_count bigint NOT NULL,
        agent_executions bigint NOT NULL,
        agent_fallbacks bigint NOT NULL,
        tool_executions bigint NOT NULL,
        tool_approvals_requested bigint NOT NULL,
        tool_approvals_resolved bigint NOT NULL,
        final_approvals_requested bigint NOT NULL,
        final_approvals_resolved bigint NOT NULL,
        handoffs bigint NOT NULL,
        rag_queries bigint NOT NULL,
        reviews bigint NOT NULL,
        avg_agent_latency_ms double precision NOT NULL,
        avg_tool_latency_ms double precision NOT NULL,
        events_by_type jsonb NOT NULL,
        agent_execution_counts jsonb NOT NULL,
        snapshot_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_runtime_metrics_snapshots" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE runtime_reflections (
        id character varying(64) NOT NULL,
        session_id character varying(128) NOT NULL,
        agent_name character varying(256) NOT NULL,
        action_taken text NOT NULL,
        outcome text NOT NULL,
        confidence double precision NOT NULL,
        deviations jsonb NOT NULL,
        lessons_learned jsonb NOT NULL,
        improvement_suggestion text,
        severity character varying(32) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_runtime_reflections" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE scheduled_task_executions (
        execution_id character varying(128) NOT NULL,
        task_id character varying(128) NOT NULL,
        started_at timestamp with time zone NOT NULL,
        completed_at timestamp with time zone,
        success boolean NOT NULL,
        payload jsonb NOT NULL,
        CONSTRAINT "PK_scheduled_task_executions" PRIMARY KEY (execution_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE scheduled_tasks (
        id character varying(128) NOT NULL,
        name text NOT NULL,
        status character varying(64) NOT NULL,
        next_run_at timestamp with time zone,
        payload jsonb NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_scheduled_tasks" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE sessions (
        id character varying(128) NOT NULL,
        user_id character varying(128) NOT NULL,
        tenant_id character varying(128) NOT NULL,
        data jsonb NOT NULL,
        started_at timestamp with time zone NOT NULL,
        ended_at timestamp with time zone,
        is_consolidated boolean NOT NULL,
        CONSTRAINT "PK_sessions" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE tenants (
        id character varying(128) NOT NULL,
        name character varying(256) NOT NULL,
        slug character varying(128) NOT NULL,
        plan character varying(32) NOT NULL,
        limits jsonb NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        provider_api_keys jsonb NOT NULL,
        settings jsonb NOT NULL,
        CONSTRAINT "PK_tenants" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE trigger_rules (
        id character varying(128) NOT NULL,
        name text NOT NULL,
        enabled boolean NOT NULL,
        payload jsonb NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_trigger_rules" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE TABLE vector_documents (
        id character varying(256) NOT NULL,
        content text NOT NULL,
        type character varying(64) NOT NULL,
        collection character varying(128) NOT NULL,
        embedding real[] NOT NULL,
        metadata jsonb NOT NULL,
        indexed_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_vector_documents" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_agent_memories_agent_name ON agent_memories (agent_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_agent_memories_last_used_at ON agent_memories (last_used_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_agent_memories_user_agent ON agent_memories (user_id, agent_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_agent_memories_user_id ON agent_memories (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_agent_metrics_agent_domain ON agent_performance_metrics (agent_name, domain);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_agent_metrics_agent_name ON agent_performance_metrics (agent_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_agent_metrics_domain ON agent_performance_metrics (domain);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_config_change_logs_key_changed_at ON config_change_logs (config_key, changed_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_config_entries_category ON config_entries (category);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE UNIQUE INDEX "IX_config_entries_key" ON config_entries (key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE UNIQUE INDEX ix_cost_budgets_tenant_service ON cost_budgets (tenant_id, service_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_cost_entries_recorded_at ON cost_entries (recorded_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_cost_entries_service_name ON cost_entries (service_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_cost_entries_tenant_id ON cost_entries (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_cost_entries_tenant_service_date ON cost_entries (tenant_id, service_name, recorded_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX idx_embedding_models_active ON embedding_models (is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX idx_embedding_models_name ON embedding_models (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX idx_migration_jobs_created ON migration_jobs (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX idx_migration_jobs_status ON migration_jobs (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_runtime_artifacts_created_at ON runtime_artifacts (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_runtime_artifacts_session_id ON runtime_artifacts (session_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_runtime_artifacts_session_type ON runtime_artifacts (session_id, type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_runtime_artifacts_type ON runtime_artifacts (type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_runtime_evaluations_agent_name ON runtime_evaluations (agent_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_runtime_evaluations_created_at ON runtime_evaluations (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_runtime_evaluations_regression ON runtime_evaluations (regression_detected);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_runtime_metrics_session_id ON runtime_metrics_snapshots (session_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_runtime_metrics_snapshot_at ON runtime_metrics_snapshots (snapshot_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_runtime_reflections_agent_name ON runtime_reflections (agent_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_runtime_reflections_created_at ON runtime_reflections (created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_runtime_reflections_session_id ON runtime_reflections (session_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_scheduled_task_executions_task_id ON scheduled_task_executions (task_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_scheduled_tasks_status ON scheduled_tasks (status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX idx_sessions_started ON sessions (started_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_sessions_tenant_id ON sessions (tenant_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_sessions_user_id ON sessions (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_tenants_is_active ON tenants (is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE UNIQUE INDEX ix_tenants_slug ON tenants (slug);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_trigger_rules_enabled ON trigger_rules (enabled);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_vector_documents_collection ON vector_documents (collection);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_vector_documents_indexed_at ON vector_documents (indexed_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    CREATE INDEX ix_vector_documents_type ON vector_documents (type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM __ef_migrations_history WHERE "MigrationId" = '20260507044443_ConsolidateEfPersistenceSchema') THEN
    INSERT INTO __ef_migrations_history ("MigrationId", "ProductVersion")
    VALUES ('20260507044443_ConsolidateEfPersistenceSchema', '10.0.7');
    END IF;
END $EF$;
COMMIT;

