import { test, expect } from '@playwright/test'

const prompt = 'Line one: "quote" # literal\n  C:\\folder\nlast line\n'
const description = 'Quoted: "review" # text\nsecond description line'

test('visual to YAML and back saves and reopens fields, quoting and multiline content', async ({ page }) => {
  let saved: Record<string, unknown> | undefined
  let savedYaml = ''
  await page.route('**/hubs/**', route => route.abort())
  await page.route('**/api/**', async route => {
    const path = new URL(route.request().url()).pathname
    if (!path.startsWith('/api/')) return route.continue()
    if (path === '/api/auth/session') return route.fulfill({ json: { userId: 'user-a', tenantId: 'tenant-a', roles: ['Owner'] } })
    if ((path === '/api/agent/agents' || path === '/api/agent/agents/all') && route.request().method() === 'GET') return route.fulfill({ json: saved ? [saved] : [] })
    if (path.endsWith('/validate-yaml') || path.endsWith('/save-yaml')) {
      const yaml = route.request().postDataJSON().yaml as string
      expect(yaml).toContain('metadata:')
      expect(yaml).toContain('execution:')
      expect(yaml).toContain('abilities:')
      expect(yaml).not.toContain('systemPrompt:')
      // Explicit API fixture for the JSON scalars generated by this UI, not a general YAML parser.
      const scalar = (key: string) => JSON.parse(yaml.split('\n').find(line => line.trimStart().startsWith(`${key}:`))!.split(':').slice(1).join(':').trim())
      const spec = {
        name: scalar('name'), description: scalar('description'), domain: scalar('domain'), tier: 2,
        instructions: scalar('instructions'), capabilities: scalar('capabilities'), allowedTools: scalar('allowedTools'),
        autonomyLevel: scalar('autonomyLevel'),
        configuration: { ...scalar('configuration'), maxConcurrency: scalar('maxConcurrency'), timeoutSeconds: scalar('timeoutSeconds') },
      }
      expect(scalar('tier')).toBe('Specialist')
      if (path.endsWith('/save-yaml')) {
        savedYaml = yaml
        saved = { ...spec, availableTools: spec.allowedTools, isActive: true, createdAt: new Date().toISOString(), lastUsedAt: new Date().toISOString() }
        return route.fulfill({ json: { agent: saved } })
      }
      return route.fulfill({ json: { isValid: true, errors: [], specification: spec } })
    }
    if (path.endsWith('/rooms')) return route.fulfill({ json: [] })
    return route.fulfill({ json: [] })
  })
  await page.goto('/agents')
  await page.getByRole('button', { name: 'Novo Agent', exact: true }).click()
  await page.getByLabel('Nome do Agente').fill('contract-agent')
  await page.getByLabel('Domínio Operacional').fill('finance')
  await page.getByLabel('Descrição Detalhada').fill(description)
  await page.getByLabel('Hierarquia (Tier)').selectOption('2')
  await page.getByLabel('Concorrência Máxima').fill('7')
  await page.getByLabel('Timeout Limite (s)').fill('123')
  await page.getByLabel('System Prompt / Diretrizes Operacionais (System Prompt)').fill(prompt)
  await page.getByRole('button', { name: 'YAML Declarativo (Avançado)' }).click()
  const editor = page.getByPlaceholder('# Insira ou edite sua configuração YAML declarativa')
  const initialYaml = await editor.inputValue()
  expect(initialYaml).toContain(`instructions: ${JSON.stringify(prompt)}`)
  expect(initialYaml).toContain(`  description: ${JSON.stringify(description)}`)
  await page.getByRole('button', { name: 'Formulário Visual', exact: true }).click()
  await expect(page.getByLabel('Descrição Detalhada')).toHaveValue(description)
  await expect(page.getByLabel('System Prompt / Diretrizes Operacionais (System Prompt)')).toHaveValue(prompt)
  await expect(page.getByLabel('Concorrência Máxima')).toHaveValue('7')
  await page.getByRole('button', { name: 'YAML Declarativo (Avançado)' }).click()
  const roundtrippedYaml = await editor.inputValue()
  expect(roundtrippedYaml).toContain('maxConcurrency: 7')
  expect(roundtrippedYaml).toContain('timeoutSeconds: 123')
  await page.getByRole('button', { name: 'Criar Novo Agente', exact: true }).click()
  await expect(page.getByText('contract-agent', { exact: true }).first()).toBeVisible()
  expect(savedYaml).toBe(roundtrippedYaml)
  await page.getByTitle('Editar').click()
  await expect(page.getByLabel('Descrição Detalhada')).toHaveValue(description)
  await expect(page.getByLabel('System Prompt / Diretrizes Operacionais (System Prompt)')).toHaveValue(prompt)
  await expect(page.getByLabel('Timeout Limite (s)')).toHaveValue('123')
  await page.getByRole('button', { name: 'YAML Declarativo (Avançado)' }).click()
  await expect(editor).toHaveValue(roundtrippedYaml)
})
